### ISSUE TITLE
libbpf-cargo tests do not work outside of the git repo

### ISSUE THREAD

**Issue by davide125** [libbpf/libbpf-rs#107]
Looks like the tests assume they're being run in the git repo, where the `libpf-rs` sources are one level up in path. This is not the case when building from the crate (e.g. when packaging this in Fedora).

```
     Running `/usr/bin/rustc --crate-name cargo_libbpf --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no --test -C metadata=0eca454eb3e06fda -C extra-filename=-0eca454eb3e06fda --out-dir /builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps -L dependency=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps --extern anyhow=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps/libanyhow-f52d6e2d8b872bc9.rlib --extern cargo_metadata=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps/libcargo_metadata-201286cef2c0f393.rlib --extern goblin=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps/libgoblin-0ee0c613fd9ed025.rlib --extern libbpf_cargo=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps/liblibbpf_cargo-555dbf843feae080.rlib --extern libbpf_sys=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps/liblibbpf_sys-03751eec0e5e8d63.rlib --extern memmap=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps/libmemmap-6b80da01316dd249.rlib --extern num_enum=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps/libnum_enum-92ef6d87fed9e797.rlib --extern regex=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps/libregex-e5e411dbb90962d5.rlib --extern scroll=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps/libscroll-ae68cbd995482dd6.rlib --extern scroll_derive=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps/libscroll_derive-58cac732bd0f41b2.so --extern semver=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps/libsemver-e24cc60083843439.rlib --extern serde=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps/libserde-a2f925a616df0a1a.rlib --extern serde_json=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps/libserde_json-f64fb15ed2340581.rlib --extern structopt=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps/libstructopt-0605240d071edd38.rlib --extern tempfile=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps/libtempfile-b2db7dd4d4b67661.rlib --extern thiserror=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps/libthiserror-7848cb14d8adb2c2.rlib -Copt-level=3 -Cdebuginfo=2 -Clink-arg=-Wl,-z,relro,-z,now -Ccodegen-units=1 --cap-lints=warn -L native=/usr/lib64 -L native=/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/build/libbpf-sys-96b26f105dc6b24f/out`
    Finished release [optimized] target(s) in 35.15s
     Running `/builddir/build/BUILD/libbpf-cargo-0.7.0/target/release/deps/libbpf_cargo-9b34da430701d3e1`

running 32 tests
test build::test_extract_version ... ok
test test::test_btf_dump_definition_anon_enum ... ok
test test::test_btf_dump_definition_datasec_multiple ... ok
test test::test_btf_dump_definition_datasec ... ok
test test::test_btf_dump_basic_long_array ... ok
test test::test_btf_dump_basic ... ok
test test::test_btf_dump_definition_datasec_long_array ... ok
test test::test_btf_dump_definition_bitfield_struct_fails ... ok
test test::test_btf_dump_definition_datasec_multiple_long_array ... ok
test test::test_btf_dump_definition_packed_struct ... ok
test test::test_btf_dump_definition_shared_dependent_types ... ok
test test::test_btf_dump_definition_packed_struct_long_array ... ok
test test::test_btf_dump_definition_enum ... ok
test test::test_btf_dump_definition_struct_inner_anon_union ... ok
test test::test_btf_dump_definition_struct_inner_anon_struct ... ok
test test::test_btf_dump_definition_struct_inner_anon_struct_and_union ... ok
test test::test_btf_dump_definition_union ... ok
test test::test_build_workspace_collision ... ok
test test::test_build_custom ... ok
test test::test_build_invalid_prog ... ok
test test::test_build_workspace ... ok
test test::test_build_default ... ok
test test::test_enforce_file_extension ... ok
test test::test_btf_dump_struct_definition ... ok
test test::test_skeleton_builder_clang_opts ... ok
test test::test_btf_dump_struct_definition_long_array ... ok
libbpf: elf: skipping unrecognized data section(13) .eh_frame
libbpf: elf: skipping relo section(14) .rel.eh_frame for section(13) .eh_frame
libbpf: elf: skipping unrecognized data section(13) .eh_frame
libbpf: elf: skipping relo section(14) .rel.eh_frame for section(13) .eh_frame
libbpf: elf: skipping unrecognized data section(13) .eh_frame
libbpf: elf: skipping relo section(14) .rel.eh_frame for section(13) .eh_frame
libbpf: elf: skipping unrecognized data section(13) .eh_frame
libbpf: elf: skipping relo section(14) .rel.eh_frame for section(13) .eh_frame
test test::test_skeleton_builder_basic ... FAILED
libbpf: elf: skipping unrecognized data section(14) .eh_frame
libbpf: elf: skipping relo section(15) .rel.eh_frame for section(14) .eh_frame
libbpf: elf: skipping unrecognized data section(14) .eh_frame
libbpf: elf: skipping relo section(15) .rel.eh_frame for section(14) .eh_frame
test test::test_make_basic has been running for over 60 seconds
test test::test_make_workspace has been running for over 60 seconds
test test::test_skeleton_basic has been running for over 60 seconds
test test::test_skeleton_datasec has been running for over 60 seconds
test test::test_skeleton_empty_source has been running for over 60 seconds
test test::test_make_basic ... ok
test test::test_make_workspace ... ok
test test::test_skeleton_empty_source ... FAILED
test test::test_skeleton_basic ... FAILED
test test::test_skeleton_datasec ... FAILED

failures:

---- test::test_skeleton_builder_basic stdout ----
clang is version 12.0.0
Building /tmp/.tmpZwVfSx/proj/src/bpf/prog.bpf.c
Warning: unrecognized map: .maps
thread 'test::test_skeleton_builder_basic' panicked at 'failed to canonicalize libbpf-rs: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/test.rs:112:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test::test_skeleton_empty_source stdout ----
Metadata for package=proj
	null
Found bpf progs to compile:
	UnprocessedObj { package: "proj", path: "/tmp/.tmp3rhryw/proj/src/bpf/prog.bpf.c", out: "/tmp/.tmp3rhryw/proj/target/bpf", name: "prog" }
Building /tmp/.tmp3rhryw/proj/src/bpf/prog.bpf.c
Metadata for package=proj
	null
Found bpf objs to gen skel:
	UnprocessedObj { package: "proj", path: "/tmp/.tmp3rhryw/proj/src/bpf/prog.bpf.c", out: "/tmp/.tmp3rhryw/proj/target/bpf", name: "prog" }
thread 'test::test_skeleton_empty_source' panicked at 'failed to canonicalize libbpf-rs: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/test.rs:112:10

---- test::test_skeleton_basic stdout ----
Metadata for package=proj
	null
Found bpf progs to compile:
	UnprocessedObj { package: "proj", path: "/tmp/.tmpf9kfDw/proj/src/bpf/prog.bpf.c", out: "/tmp/.tmpf9kfDw/proj/target/bpf", name: "prog" }
Building /tmp/.tmpf9kfDw/proj/src/bpf/prog.bpf.c
Metadata for package=proj
	null
Found bpf objs to gen skel:
	UnprocessedObj { package: "proj", path: "/tmp/.tmpf9kfDw/proj/src/bpf/prog.bpf.c", out: "/tmp/.tmpf9kfDw/proj/target/bpf", name: "prog" }
Warning: unrecognized map: .maps
thread 'test::test_skeleton_basic' panicked at 'failed to canonicalize libbpf-rs: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/test.rs:112:10

---- test::test_skeleton_datasec stdout ----
Metadata for package=proj
	null
Found bpf progs to compile:
	UnprocessedObj { package: "proj", path: "/tmp/.tmpcwUAUo/proj/src/bpf/prog.bpf.c", out: "/tmp/.tmpcwUAUo/proj/target/bpf", name: "prog" }
Building /tmp/.tmpcwUAUo/proj/src/bpf/prog.bpf.c
Metadata for package=proj
	null
Found bpf objs to gen skel:
	UnprocessedObj { package: "proj", path: "/tmp/.tmpcwUAUo/proj/src/bpf/prog.bpf.c", out: "/tmp/.tmpcwUAUo/proj/target/bpf", name: "prog" }
thread 'test::test_skeleton_datasec' panicked at 'failed to canonicalize libbpf-rs: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/test.rs:112:10


failures:
    test::test_skeleton_basic
    test::test_skeleton_builder_basic
    test::test_skeleton_datasec
    test::test_skeleton_empty_source

test result: FAILED. 28 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 126.61s
```

**Comment by danobi** [comment]
I left this comment in the code when I added the tests:
https://github.com/libbpf/libbpf-rs/blob/ff02672b2f1cdf73a770d3c87c9ebf2ddd21e575/libbpf-cargo/src/test.rs#L99-L103

We need the local libbpf-rs so that the libbpf-cargo tests stay in sync.

I guess we could add an environment variable to control the location of libbpf-rs but that's also suboptimal. WDYT?

**Comment by davide125** [comment]
Yeah, an env variable would work I think; you probably want to also document this in the README. Not sure if there's a better / more straightforward way to handle this...

**Comment by danobi** [comment]
The packaging system still uses cargo, right? If so, can you share the cargo command they use? Just wanna see if there's better options first

**Comment by davide125** [comment]
Yeah, it uses cargo. The macro is this one: https://pagure.io/fedora-rust/rust2rpm/blob/master/f/data/macros.cargo#_70 but I can't get it to spit out the actual command it's running.

**Comment by danobi** [comment]
Lol I can't even guess what that expands to. I just tried
```
$ cargo test --manifest-path libbpf-rs/libbpf-cargo/Cargo.toml
```

from outside the git repo and that still worked. Must be some other weird invocation

**Comment by davide125** [comment]
It's running `/usr/bin/cargo test -j8 -Z avoid-dev-deps --release --no-fail-fast` from the crate (not from the git repo).

**Comment by danobi** [comment]
Oh I see. So the `libbpf-rs` (crate) source probably isn't even available. So would an env var even help?

**Comment by davide125** [comment]
It's available as part of the devel package: https://koji.fedoraproject.org/koji/rpminfo?rpmID=26352823 which is pulled in as a build dependency

**Comment by willfindlay** [comment]
What about falling back to the crates.io version if `get_libbpf_rs_path()` fails?

**Comment by danobi** [comment]
@davide125 are there any instructions for how to reproduce locally? cargo sets a bunch of handy env variables which I think I can make work but I need to know the directory structure of the koji builds.

**Comment by danobi** [comment]
> What about falling back to the crates.io version if get_libbpf_rs_path() fails?

Hmm, I don't love the idea of downloading from the internet for unit tests. And especially if you're making a local change that spans libbpf-rs and libbpf-cargo things could go weird.

**Comment by davide125** [comment]
Fedora builds don't have access to the Internet (that's true for most distros actually). You can repro a build on any Fedora box with `mock` installed, using:
```
mock -r fedora-rawhide-x86_64 --with=check https://dcavalca.fedorapeople.org/review/rust-libbpf-cargo/rust-libbpf-cargo-0.7.0-1.fc35.src.rpm
```
This will fail the tests (drop the `--with=check` if you want it to skip tests and complete successfully). You can then use
```
mock -r fedora-rawhide-x86_64 --shell
```
to inspect the build environment. If you need extra packages for troubleshooting you can get them installed with
```
mock -r fedora-rawhide-x86_64 --install vim-enhanced
```

https://bugzilla.redhat.com/show_bug.cgi?id=1967326 also has a link to the specfile that was used to build that `src.rpm`.

**Comment by danobi** [comment]
Chatted offline: probably makes the most sense to disable the integration tests during packaging

**Comment by davide125** [comment]
This seems to be doing the trick:
```
%cargo_test -- -- \
    --skip test_skeleton_basic \
    --skip test_skeleton_builder_basic \
    --skip test_skeleton_datasec \
    --skip test_skeleton_empty_source
````
