### ISSUE TITLE
Cannot build example

### ISSUE THREAD

**Issue by nurdann** [libbpf/libbpf-rs#300]
Ran
```
$ git clone https://github.com/libbpf/libbpf-rs.git
$ cd libbpf-rs/examples/runqslower/
$ cargo build
 Downloading crates ...
  Downloaded plain v0.2.3
  Downloaded num_threads v0.1.6
  Downloaded once_cell v1.15.0
  Downloaded quote v1.0.21
  Downloaded os_str_bytes v6.3.0
  Downloaded proc-macro2 v1.0.47
  Downloaded rustversion v1.0.9
  Downloaded semver v1.0.14
  Downloaded thiserror v1.0.37
  Downloaded thiserror-impl v1.0.37
  Downloaded ryu v1.0.11
  Downloaded textwrap v0.15.1
  Downloaded serde_derive v1.0.147
  Downloaded serde v1.0.147
  Downloaded regex v1.6.0
  Downloaded time-macros v0.2.4
  Downloaded serde_json v1.0.87
  Downloaded toml v0.5.9
  Downloaded pkg-config v0.3.25
  Downloaded syn v1.0.103
  Downloaded regex-syntax v0.6.27
  Downloaded itoa v1.0.4
  Downloaded indexmap v1.9.1
  Downloaded anyhow v1.0.66
  Downloaded memmap2 v0.5.7
  Downloaded time v0.3.15
  Downloaded cc v1.0.73
  Downloaded clap v3.2.22
  Downloaded unicode-ident v1.0.5
  Downloaded nix v0.24.2
  Downloaded libc v0.2.135
  Downloaded libbpf-sys v1.0.3+v1.0.1
   Compiling proc-macro2 v1.0.47
   Compiling quote v1.0.21
   Compiling unicode-ident v1.0.5
   Compiling syn v1.0.103
   Compiling serde_derive v1.0.147
   Compiling serde v1.0.147
   Compiling autocfg v1.1.0
   Compiling version_check v0.9.4
   Compiling libc v0.2.135
   Compiling cc v1.0.73
   Compiling thiserror v1.0.37
   Compiling once_cell v1.15.0
   Compiling pkg-config v0.3.25
   Compiling serde_json v1.0.87
   Compiling cfg-if v1.0.0
   Compiling camino v1.1.1
   Compiling semver v1.0.14
   Compiling itoa v1.0.4
   Compiling bitflags v1.3.2
   Compiling heck v0.4.0
   Compiling anyhow v1.0.66
   Compiling hashbrown v0.12.3
   Compiling ryu v1.0.11
   Compiling os_str_bytes v6.3.0
   Compiling rustversion v1.0.9
   Compiling regex-syntax v0.6.27
   Compiling remove_dir_all v0.5.3
   Compiling textwrap v0.15.1
   Compiling fastrand v1.8.0
   Compiling scroll v0.11.0
   Compiling unicode-segmentation v1.10.0
   Compiling num_threads v0.1.6
   Compiling time-macros v0.2.4
   Compiling lazy_static v1.4.0
   Compiling plain v0.2.3
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.9.1
   Compiling memoffset v0.6.5
   Compiling clap_lex v0.2.4
   Compiling libbpf-sys v1.0.3+v1.0.1
   Compiling vsprintf v2.0.0
   Compiling heck v0.3.3
   Compiling regex v1.6.0
error: failed to run custom build command for `libbpf-sys v1.0.3+v1.0.1`

Caused by:
  process didn't exit successfully: `/home/qq/repos/libbpf-rs/target/debug/build/libbpf-sys-d2368875d1c97a90/build-script-build` (exit status: 101)
  --- stderr
  make: *** No targets specified and no makefile found.  Stop.
  thread 'main' panicked at 'pkg-config is required to compile libbpf-sys using the vendored copy of libbpf', /home/qq/.cargo/registry/src/github.com-1ecc6299db9ec823/libbpf-sys-1.0.3+v1.0.1/build.rs:107:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```
 on
```
$ uname -r
5.15.0-56-generic
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04 LTS
Release:	22.04
Codename:	jammy
```

Am I missing something? Any idea how to resolve this?

**Comment by danielocfb** [comment]
> panicked at 'pkg-config is required to compile libbpf-sys using the vendored copy of libbpf'

Sounds as if `pkg-config` is a requirement. Have you tried installing it?

**Comment by nurdann** [comment]
Installed `apt install pkgconf` but now getting another error (on `master`)
```
$ RUST_BACKTRACE=1 cargo build
   Compiling runqslower v0.1.0 (/home/qq/repos/libbpf-rs/examples/runqslower)
error: failed to run custom build command for `runqslower v0.1.0 (/home/qq/repos/libbpf-rs/examples/runqslower)`

Caused by:
  process didn't exit successfully: `/home/qq/repos/libbpf-rs/target/debug/build/runqslower-33aaf9d06b208546/build-script-build` (exit status: 101)
  --- stderr
  Warning: unrecognized map: .maps
  Warning: unrecognized map: license
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Generate("Failed to generate skeleton for /tmp/.tmpzJIUt5/runqslower.o: Failed to spawn rustfmt")', examples/runqslower/build.rs:13:10
  stack backtrace:
     0: rust_begin_unwind
               at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/panicking.rs:143:14
     2: core::result::unwrap_failed
               at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/result.rs:1785:5
     3: core::result::Result<T,E>::unwrap
               at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/result.rs:1078:23
     4: build_script_build::main
               at ./build.rs:10:5
     5: core::ops::function::FnOnce::call_once
               at /build/rustc-ZOqcvC/rustc-1.61.0+dfsg1/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by danielocfb** [comment]
You'll need to install `rustfmt` as well.

**Comment by nurdann** [comment]
Thanks, it worked! So I needed to install these on Ubuntu before `cargo build`
```
sudo apt install libelf-dev pkgconf rustfmt 
```
Is it possible to make it explicit in the documentation?

**Comment by danielocfb** [comment]
> Thanks, it worked! So I needed to install these on Ubuntu before `cargo build`
> 
> ```
> sudo apt install libelf-dev pkgconf rustfmt 
> ```

`pkgconf` isn't a `libbpf-rs` dependency, but a `libbpf-sys` thing, so that's on them. I feel like the error emitted is pretty self-descriptive and may not warrant getting into distribution specific package names etc. That said, if you feel strongly I'd suggest opening an issue over [there](https://github.com/libbpf/libbpf-sys).

For `rustfmt`, I've hit that issue several times myself. I think we should just make it optional altogether, because I think it should not have to be a hard dependency. I am working on it.

As for `libelf-dev`, I don't have a way to test out what the error is or which component it needs to really make a call here. Can you share details what issue you saw, please?

**Comment by nurdann** [comment]
`libelf-dev` is a dependency for `libbpf-sys` so not directly related to `libbpf-rs`. So you can consider this issue resolved.
```
examples/runqslower$ cargo build
   Compiling proc-macro2 v1.0.47
   Compiling unicode-ident v1.0.5
   Compiling quote v1.0.21
   Compiling syn v1.0.103
   Compiling serde_derive v1.0.147
   Compiling serde v1.0.147
   Compiling autocfg v1.1.0
   Compiling version_check v0.9.4
   Compiling libc v0.2.135
   Compiling cc v1.0.73
   Compiling thiserror v1.0.37
   Compiling once_cell v1.15.0
   Compiling pkg-config v0.3.25
   Compiling cfg-if v1.0.0
   Compiling itoa v1.0.4
   Compiling camino v1.1.1
   Compiling bitflags v1.3.2
   Compiling semver v1.0.14
   Compiling serde_json v1.0.87
   Compiling anyhow v1.0.66
   Compiling hashbrown v0.12.3
   Compiling heck v0.4.0
   Compiling ryu v1.0.11
   Compiling os_str_bytes v6.3.0
   Compiling textwrap v0.15.1
   Compiling remove_dir_all v0.5.3
   Compiling regex-syntax v0.6.27
   Compiling fastrand v1.8.0
   Compiling rustversion v1.0.9
   Compiling unicode-segmentation v1.10.0
   Compiling scroll v0.11.0
   Compiling time-macros v0.2.4
   Compiling num_threads v0.1.6
   Compiling lazy_static v1.4.0
   Compiling plain v0.2.3
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling indexmap v1.9.1
   Compiling memoffset v0.6.5
   Compiling clap_lex v0.2.4
   Compiling libbpf-sys v1.0.3+v1.0.1
   Compiling vsprintf v2.0.0
   Compiling heck v0.3.3
   Compiling regex v1.6.0
error: failed to run custom build command for `libbpf-sys v1.0.3+v1.0.1`

Caused by:
  process didn't exit successfully: `/home/qq/repos/libbpf-rs/target/debug/build/libbpf-sys-d2368875d1c97a90/build-script-build` (exit status: 101)
  --- stdout
  OPT_LEVEL = Some("0")
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
    MKDIR    /home/qq/repos/libbpf-rs/target/debug/build/libbpf-sys-c33650c428513b7f/out/obj/staticobjs
    CC       /home/qq/repos/libbpf-rs/target/debug/build/libbpf-sys-c33650c428513b7f/out/obj/staticobjs/bpf.o
    CC       /home/qq/repos/libbpf-rs/target/debug/build/libbpf-sys-c33650c428513b7f/out/obj/staticobjs/btf.o

  --- stderr
  make: *** No targets specified and no makefile found.  Stop.
  Please specify at least one package name on the command line.
  Package libelf was not found in the pkg-config search path.
  Perhaps you should add the directory containing `libelf.pc'
  to the PKG_CONFIG_PATH environment variable
  Package 'libelf', required by 'virtual:world', not found
  bpf.c: In function ‘alloc_zero_tailing_info’:
  bpf.c:219:23: warning: comparison of integer expressions of different signedness: ‘int’ and ‘__u32’ {aka ‘unsigned int’} [-Wsign-compare]
    219 |         for (i = 0; i < cnt; i++) {
        |                       ^
  btf.c:18:10: fatal error: gelf.h: No such file or directory
     18 | #include <gelf.h>
        |          ^~~~~~~~
  compilation terminated.
  make: *** [Makefile:130: /home/qq/repos/libbpf-rs/target/debug/build/libbpf-sys-c33650c428513b7f/out/obj/staticobjs/btf.o] Error 1
  thread 'main' panicked at 'make failed', /home/qq/.cargo/registry/src/github.com-1ecc6299db9ec823/libbpf-sys-1.0.3+v1.0.1/build.rs:134:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

**Comment by danielocfb** [comment]
> `libelf-dev` is a dependency for `libbpf-sys` so not directly related to `libbpf-rs`. So you can consider this issue resolved.

Great, thank you!
